# Generated by Django 2.2.28 on 2022-08-26 10:24

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name must be unique.', max_length=120, unique=True, verbose_name='Crew Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name'], unique=True)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'List of All Crews',
                'ordering': ('name',),
            },
        ),
    ]
