# Generated by Django 2.2.28 on 2022-08-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackerinput',
            options={'ordering': ('name',), 'verbose_name': 'Roof Type', 'verbose_name_plural': 'List of All Tracker Input Types'},
        ),
    ]
