# Generated by Django 2.2.28 on 2022-09-17 23:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trackers.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crews', '0001_initial'),
        ('roofs', '0001_initial'),
        ('trackers', '0002_auto_20220826_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job_code', models.CharField(max_length=250, unique=True, validators=[trackers.validators.job_code_validator], verbose_name='Job Code')),
                ('customer_name', models.CharField(max_length=250, verbose_name='Customer Name')),
                ('system_size', models.DecimalField(decimal_places=2, help_text='In kW', max_digits=20, verbose_name='System Size')),
                ('number_of_panels', models.PositiveIntegerField(verbose_name='Number of Panels')),
                ('number_of_arrays', models.PositiveIntegerField(verbose_name='Number of Arrays')),
                ('is_battery', models.BooleanField(default=False)),
                ('number_of_batteries', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(blank=True, choices=[('roof', 'Roof'), ('ground', 'Ground')], default='', max_length=10, null=True)),
                ('number_of_workers', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crews.Crew')),
                ('roof_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roofs.RoofType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Tracker',
                'verbose_name_plural': 'Customer Trackers',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='InitialJobProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('position', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(choices=[('roof', 'Roof'), ('ground', 'Ground')], max_length=10)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Initial Job Process',
                'verbose_name_plural': 'Initial Job Processes',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='JobProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('position', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('customer_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_processes', to='trackers.CustomerTracker')),
            ],
            options={
                'verbose_name': 'Job Process',
                'verbose_name_plural': 'Job Processes',
                'ordering': ('position',),
            },
        ),
    ]
