# Generated by Django 2.2.28 on 2022-10-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_customertracker_initialjobprocess_jobprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprocess',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
