# Generated by Django 2.2.28 on 2022-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0004_jobprocess_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprocess',
            name='time_spent_seconds',
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='Paused'),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='last_paused_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Paused Time'),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='total_paused_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
