# Generated by Django 2.2.28 on 2022-10-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_auto_20221006_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprocess',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobprocess',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='jobprocess',
            name='is_paused',
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Closed'), ('paused', 'Paused')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
