# Generated by Django 2.2.28 on 2022-10-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0006_auto_20221012_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprocess',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Closed'), ('paused', 'Paused')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
