# Generated by Django 2.2.28 on 2022-10-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0007_auto_20221012_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprocess',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Closed'), ('paused', 'Paused')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='customertracker',
            constraint=models.UniqueConstraint(condition=models.Q(status='active'), fields=('status', 'user'), name='user_customer_tracker_active_unique'),
        ),
    ]
