# Generated by Django 2.2.28 on 2022-10-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0008_auto_20221013_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprocess',
            name='resuming_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resuming Time'),
        ),
    ]
