# Generated by Django 2.2.28 on 2022-11-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0009_jobprocess_resuming_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertracker',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_trackers', to='crews.Crew'),
        ),
        migrations.AlterField(
            model_name='customertracker',
            name='roof_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_trackers', to='roofs.RoofType'),
        ),
    ]
