# Generated by Django 2.2.28 on 2022-11-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0010_auto_20221118_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprocess',
            name='seconds_per_job',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Seconds Per Job'),
        ),
    ]
