# Generated by Django 2.2.28 on 2022-11-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0011_jobprocess_seconds_per_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertracker',
            name='seconds_per_kw',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Seconds Per kW'),
        ),
    ]
