# Generated by Django 2.2.28 on 2022-08-26 08:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220825_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.user_profile_picture_path, verbose_name='Profile Picture'),
        ),
    ]
