# Generated by Django 2.2.28 on 2022-08-26 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0001_initial'),
        ('users', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crews.Crew'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(blank=True, choices=[('TXS', 'TXS'), ('NJC', 'NJC'), ('NYS', 'NYS'), ('CIL', 'CIL'), ('NYH', 'NYH'), ('MAW', 'MAW'), ('VER', 'VER'), ('NMA', 'NMA'), ('TMA', 'TMA'), ('MAS', 'MAS'), ('MAE', 'MAE'), ('CON', 'CON'), ('CTS', 'CTS'), ('MDE', 'MDE'), ('MDT', 'MDT'), ('MDN', 'MDN'), ('DEN', 'DEN'), ('CHS', 'CHS'), ('ILC', 'ILC'), ('NJT', 'NJT'), ('OFL', 'OFL'), ('TFL', 'TFL'), ('NJS', 'NJS'), ('DTX', 'DTX'), ('HTX', 'HTX'), ('PHS', 'PHS'), ('PHX', 'PHX'), ('SAC', 'SAC'), ('NBA', 'NBA'), ('DBA', 'DBA'), ('SBA', 'SBA'), ('MBA', 'MBA'), ('EBA', 'EBA'), ('STC', 'STC'), ('SCN', 'SCN'), ('FRS', 'FRS'), ('CVC', 'CVC'), ('BAK', 'BAK'), ('NSD', 'NSD'), ('SDO', 'SDO'), ('SSD', 'SSD'), ('ORC', 'ORC'), ('SLA', 'SLA'), ('LOS', 'LOS'), ('SLO', 'SLO'), ('CAM', 'CAM')], default='', max_length=10, null=True, verbose_name='Branch')),
                ('job_title', models.CharField(blank=True, choices=[('installed', 'Installer'), ('lead_installer', 'Lead Installer'), ('foreman', 'Foreman'), ('electrician', 'Electrician'), ('pv_installer', 'PV Installer')], default='', max_length=20, null=True, verbose_name='Job Title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ('user__username',),
            },
        ),
    ]
